### ISSUE TITLE
Unable to push/publish Visual Studio Code file into Power Apps. Lab 5, exercise 2, task 1.

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#67] opened 2023-02-02 15:16 UTC
#### Step: 3

Description of issue: After completing the rest of this lab multiple times to ensure accuracy, we are unable to use the command "pac pcf push --publisher-prefix contoso" without facing errors. 

Errors:
- Error: Building temporary solution wrapper: failed. See obj\build.log for more details.
- The OutputPath property is not set for project 'PowerAppsTools_contoso.cdsproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.

We also tried to run this before the publish command just to see if there were any steps missing that we could recommend adding but it didn't work for us: msbuild /p:configuration=Release 

We were trying to see if there was anyone else having the same issue and how we could resolve it, but we were not successful and all posts we found were related to old versions that we're not using at the moment. All posts were about version 1.16 but we're on latest (1.21.8). We tried switching between versions just in case but that didn't work either so we think it's probably something else that we're missing.

Repro steps:

1. In Visual Studio Code, within the SRC directory in the terminal, I enter "pac auth create --url <Environment URL>" and authenticate successfully.
2. The next step as mentioned above, fails with the errors listed.

**Comment by LewisGoDeploy** [comment] 2023-02-07 08:09
Any chance I could get an update on this please? We have customers who are unable to follow the guides successfully in a lab environment due to this problem.

**Comment by fz6** [comment] 2023-02-08 16:13
Having the same experience as a student on this course. Doesn't give a great impression of the product or how it is supported :-1:

**Comment by KaterinaGD** [comment] 2023-02-14 16:44
Hi @skulthm-ms, is there any chance we can get an update on this soon, please? We are a training provider and have students currently taking part in MCT-lead classes and they are unable to complete the virtual lab environment based on the steps in this guide. As I'm sure you can understand, this leads to frustration from training providers and the students themselves who have paid to take part in these courses. We would greatly appreciate your assistance.

**Comment by glissom** [comment] 2023-02-15 06:04
Modified the cdsproj file here: 
obj\PowerAppsTools_contoso\PowerAppsTools_contoso.cdsproj

Added a new propertygroup with the OutputPath Property

`<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
<DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>`

**Comment by julians1966** [comment] 2023-03-07 10:01
Move the PowerApps CLI install before developer command prompt is opened, or close and restart the developer command prompt
The PowerApps CLI install adds items to the PATH and this might be what you are missing

**Comment by DanePillay-nel** [comment] 2023-03-22 18:41
So I tried the following and got mine to work.
I merged the code with the first Propertygroup.

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup> <PowerAppsTargetsPath>$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\PowerApps</PowerAppsTargetsPath>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType> 
    <Optimize>false</Optimize> 
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants> 
    <ErrorReport>prompt</ErrorReport> 
    <WarningLevel>4</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors> 
  </PropertyGroup>

**Comment by skulthm-ms** [comment] 2023-03-28 22:24
We didn't encounter this issue in the recent test. Please follow julians advice and if that didnt work please let us know if DanePillay-nel solution or glissom is working for you. I really appreciate everyone's input here. Sometimes we can't reproduce the issue and your knowledge sharing is the only way to debug it.

**Closed by skulthm-ms** 2023-03-28 22:24 UTC
